<?xml version="1.0" encoding="utf-8"?><Database Name="Bookstore" Class="dbBookStoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-7ALUCCQ;Initial Catalog=Bookstore;Integrated Security=True" SettingsObjectName="BookStore.Properties.Settings" SettingsPropertyName="BookstoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.vUnderStock" Member="vUnderStocks">
    <Type Name="vUnderStock">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TonKho" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vLiteraryLines" Member="vLiteraryLines">
    <Type Name="vLiteraryLine">
      <Column Name="KhuVuc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoSach" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.spDangNhap" Method="spDangNhap">
    <Parameter Name="TenDN" Parameter="tenDN" Type="System.String" DbType="NChar(9)" />
    <Parameter Name="Pass" Parameter="pass" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spDangNhapResult">
      <Column Name="CongViec" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayChiSachTheoMa" Method="spLayChiSachTheoMa">
    <Parameter Name="mas" Type="System.Int32" DbType="Int" />
    <ElementType Name="spLayChiSachTheoMaResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgonNgu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KhuVuc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TheLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KeSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaGoc" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TonKho" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LuotMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayDongSach" Method="spLayDongSach">
    <ElementType Name="spLayDongSachResult">
      <Column Name="KhuVuc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayInfo" Method="spLayInfo">
    <Parameter Name="MaNV" Parameter="maNV" Type="System.String" DbType="NChar(9)" />
    <ElementType Name="spLayInfoResult">
      <Column Name="MaNV" Type="System.String" DbType="NChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CongViec" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayMaGG" Method="spLayMaGG">
    <ElementType Name="spLayMaGGResult">
      <Column Name="MaGiamGia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayNCC" Method="spLayNCC">
    <ElementType Name="spLayNCCResult">
      <Column Name="MaNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayNV" Method="spLayNV">
    <ElementType Name="spLayNVResult">
      <Column Name="MaNV" Type="System.String" DbType="NChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CongViec" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLaySachTheoTen" Method="spLaySachTheoTen">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="spLaySachTheoTenResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgonNgu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KhuVuc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TheLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KeSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaGoc" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TonKho" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LuotMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayTenDangNhap" Method="spLayTenDangNhap">
    <ElementType Name="spLayTenDangNhapResult">
      <Column Name="Username" Type="System.String" DbType="NChar(9) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayTenNV" Method="spLayTenNV">
    <Parameter Name="manv" Type="System.String" DbType="NChar(9)" />
    <ElementType Name="spLayTenNVResult">
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayTenSach" Method="spLayTenSach">
    <ElementType Name="spLayTenSachResult">
      <Column Name="Ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayTenTacGia" Method="spLayTenTacGia">
    <ElementType Name="spLayTenTacGiaResult">
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSuaNCC" Method="spSuaNCC">
    <Parameter Name="mancc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dc" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spSuaNV2" Method="spSuaNV2">
    <Parameter Name="manv" Type="System.String" DbType="NChar(9)" />
    <Parameter Name="hoten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="congviec" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="path" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spSuaSach" Method="spSuaSach">
    <Parameter Name="masach" Type="System.Int32" DbType="Int" />
    <Parameter Name="tensach" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="tacgia" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ngonngu" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="nxb" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="khuvuc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="theloai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="kesach" Type="System.Int32" DbType="Int" />
    <Parameter Name="giagoc" Type="System.Decimal" DbType="Money" />
    <Parameter Name="giaban" Type="System.Decimal" DbType="Money" />
    <Parameter Name="tonkho" Type="System.Int32" DbType="Int" />
    <Parameter Name="code" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="path" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spThemMaGGTheoDongSach" Method="spThemMaGGTheoDongSach">
    <Parameter Name="dongs" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="code" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spThemNCC" Method="spThemNCC">
    <Parameter Name="mancc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dc" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spThemNV" Method="spThemNV">
    <Parameter Name="manv" Type="System.String" DbType="NChar(9)" />
    <Parameter Name="hoten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="congviec" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="path" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spThemSach" Method="spThemSach">
    <Parameter Name="tensach" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="tacgia" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngonngu" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="nxb" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="khuvuc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="theloai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="kesach" Type="System.Int32" DbType="Int" />
    <Parameter Name="giagoc" Type="System.Decimal" DbType="Money" />
    <Parameter Name="giaban" Type="System.Decimal" DbType="Money" />
    <Parameter Name="tonkho" Type="System.Int32" DbType="Int" />
    <Parameter Name="path" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spXoaNCC" Method="spXoaNCC">
    <Parameter Name="mancc" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spXoaNVTheoMa" Method="spXoaNVTheoMa">
    <Parameter Name="manv" Type="System.String" DbType="NChar(9)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spXoaSach" Method="spXoaSach">
    <Parameter Name="MaS" Parameter="maS" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLayChiTietSach" Method="spLayChiTietSach">
    <ElementType Name="spLayChiTietSachResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgonNgu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KhuVuc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TheLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KeSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaGoc" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TonKho" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LuotMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSuaNV1" Method="spSuaNV1">
    <Parameter Name="manv" Type="System.String" DbType="NChar(9)" />
    <Parameter Name="hoten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="congviec" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="path" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLayKhachHang" Method="spLayKhachHang">
    <ElementType Name="spLayKhachHangResult">
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayChiTietMaGG" Method="spLayChiTietMaGG">
    <Parameter Name="magg" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spLayChiTietMaGGResult">
      <Column Name="MaGiamGia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ChiTiet" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhanTramGiam" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGoMaGG" Method="spGoMaGG">
    <Parameter Name="magg" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spThemHD" Method="spThemHD">
    <Parameter Name="mahd" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="tong" Type="System.Decimal" DbType="Money" />
    <Parameter Name="makh" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="manv" Type="System.String" DbType="NChar(9)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spThemChiTietHD" Method="spThemChiTietHD">
    <Parameter Name="mahd" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="masach" Type="System.Int32" DbType="Int" />
    <Parameter Name="sl" Type="System.Int32" DbType="Int" />
    <Parameter Name="thanhtien" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLayHoaDon" Method="spLayHoaDon">
    <ElementType Name="spLayHoaDonResult">
      <Column Name="MaHD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Tong" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="NChar(9) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayChiTietHD" Method="spLayChiTietHD">
    <Parameter Name="mahd" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spLayChiTietHDResult">
      <Column Name="MaHD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spThemLuotMua" Method="spThemLuotMua">
    <Parameter Name="masach" Type="System.Int32" DbType="Int" />
    <Parameter Name="luotmua" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fnBestSellers" Method="fnBestSellers" IsComposable="true">
    <ElementType Name="fnBestSellersResult">
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Purchase" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayHDTheoThang" Method="spLayHDTheoThang">
    <Parameter Name="thang" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="nam" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spLayHDTheoThangResult">
      <Column Name="MaHD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Tong" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="NChar(9) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayDoanhThu" Method="spLayDoanhThu">
    <Parameter Name="nam" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="spLayDoanhThuResult">
      <Column Name="Thang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ThuNhap" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.fnSoKH" Method="fnSoKH" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fnSoSach" Method="fnSoSach" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLaySachTheoNCC" Method="spLaySachTheoNCC">
    <Parameter Name="ncc" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spLaySachTheoNCCResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgonNgu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KhuVuc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TheLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KeSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaGoc" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TonKho" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LuotMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spThemNH" Method="spThemNH">
    <Parameter Name="madon" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngaylap" Type="System.DateTime" DbType="Date" />
    <Parameter Name="nguoilap" Type="System.String" DbType="NChar(9)" />
    <Parameter Name="ncc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tong" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spThemChiTietNH" Method="spThemChiTietNH">
    <Parameter Name="madon" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="masach" Type="System.Int32" DbType="Int" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Parameter Name="thanhtien" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fnLayMaNH" Method="fnLayMaNH" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.spLayNH" Method="spLayNH">
    <ElementType Name="spLayNHResult">
      <Column Name="MaDon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NguoiLap" Type="System.String" DbType="NChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="NCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tong" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NguoiNhan" Type="System.String" DbType="NChar(9)" CanBeNull="true" />
      <Column Name="ViTri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayChiTietNH" Method="spLayChiTietNH">
    <Parameter Name="madon" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spLayChiTietNHResult">
      <Column Name="MaDon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayNHTheoNCC" Method="spLayNHTheoNCC">
    <Parameter Name="mancc" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spLayNHTheoNCCResult">
      <Column Name="MaDon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NguoiLap" Type="System.String" DbType="NChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="NCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tong" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NguoiNhan" Type="System.String" DbType="NChar(9)" CanBeNull="true" />
      <Column Name="ViTri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSuaNH" Method="spSuaNH">
    <Parameter Name="madon" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngaynhan" Type="System.DateTime" DbType="Date" />
    <Parameter Name="nguoinhan" Type="System.String" DbType="NChar(9)" />
    <Parameter Name="vitri" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fnSoNV" Method="fnSoNV" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLayKH" Method="spLayKH">
    <ElementType Name="spLayKHResult">
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiemTich" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spThemKh" Method="spThemKh">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="d" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spSuaKH" Method="spSuaKH">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="d" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spXoaKH" Method="spXoaKH">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLayDiemKH" Method="spLayDiemKH" IsComposable="true">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLayKHTheoMa" Method="spLayKHTheoMa">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="spLayKHTheoMaResult">
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiemTich" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spThemSLSach" Method="spThemSLSach">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="sl" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLayGG" Method="spLayGG">
    <ElementType Name="spLayGGResult">
      <Column Name="MaGiamGia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ChiTiet" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhanTramGiam" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLayGG" Method="spLayGG1">
    <ElementType Name="spLayGGResult1">
      <Column Name="MaGiamGia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ChiTiet" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhanTramGiam" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSuaMGG" Method="spSuaMGG">
    <Parameter Name="MaMgg" Parameter="maMgg" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ngaybatdau" Parameter="ngaybatdau" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Ngayketthuc" Parameter="ngayketthuc" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Chitiet" Parameter="chitiet" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Phantramgiam" Parameter="phantramgiam" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spThemMGG" Method="spThemMGG">
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ngaybatdau" Parameter="ngaybatdau" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Ngayketthuc" Parameter="ngayketthuc" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Chitiet" Parameter="chitiet" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Phantramgiam" Parameter="phantramgiam" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spXoaMGG" Method="spXoaMGG">
    <Parameter Name="code" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLayDoanhThu2" Method="spLayDoanhThu2">
    <ElementType Name="spLayDoanhThu2Result">
      <Column Name="Thang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TienBanSach" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TienNhapHang" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ThuNhap" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spThemDoanhThu" Method="spThemDoanhThu">
    <Parameter Name="thangnam" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="banhang" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="nhaphang" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="doanhthuthang" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fnLayTienNH" Method="fnLayTienNH" IsComposable="true">
    <Parameter Name="m" Type="System.Int32" DbType="Int" />
    <Parameter Name="y" Type="System.Int32" DbType="Int" />
    <Return Type="System.Decimal" />
  </Function>
  <Function Name="dbo.spXoaDoanhThu" Method="spXoaDoanhThu">
    <Parameter Name="thang" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fnKiemTraSL" Method="fnKiemTraSL" IsComposable="true">
    <Parameter Name="mas" Type="System.Int32" DbType="Int" />
    <Parameter Name="sl" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDieuChinhSLSach" Method="spDieuChinhSLSach">
    <Parameter Name="mas" Type="System.Int32" DbType="Int" />
    <Parameter Name="sl" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLayChucVu" Method="spLayChucVu">
    <ElementType Name="spLayChucVuResult">
      <Column Name="CongViec" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>